
##' This function takes an alignment (with partition information if
##' needed), a tree, and simulate datasets under a given model
##' according to the guide tree provided. Each partition is optimized
##' on the guide tree for all the model parameters (transition rates,
##' base frequencies, gamma parameter, and proportion of invariants).
##'
##' This function is used for its side effect, as it generates
##' replicated simulated datasets.
##' @title Generate Simulated alignements
##' @param algfile The original alignment file, can be in any format supported by ape:::read.dna
##' @param partfile The partition file (at this stage only RAxML partition files are supported)
##' @param tree A tree file in Newick format
##' @param model The model of molecular evolution to be used for
##' parameter estimation on each parameters (at this stage, only
##' GTRGAMMA and GTRGAMMAI are supported).
##' @param nreps Number of replicated simulated datasets to generate
##' @param formatin The alignment format needs to be a format supported by ape::read.dna
##' @param path Path where the files generated by this function will be written
##' @param raxmlCmd Which RAxML flavor do you want to use? (default raxmlHPC-PTHREADS-SSE)
##' @param raxmlArg Additional arguments to be passed to RAxML
##' @return Invisibly returns some (possibly) useful location of files
##' used and generated by this sequence.
##' @author Francois Michonneau
generateAlignments <- function(algfile, partfile, tree, model, nreps,
                        formatin="sequential", path=".",
                        raxmlCmd="raxmlHPC-PTHREADS-SSE3",
                        raxmlArg="-T7") {
    ## TODO
    ## - create tests to make sure that there are no files that match
    ##   the regexpr used in the code before we start
    ## - possibility of changing seq-gen output format

    stopifnot(file.exists("seq-gen"))
    model <- match.arg(model, c("GTRGAMMA", "GTRGAMMAI"))
    
    owd <- getwd()
    setwd(path)

    ## Cut Alignment
    cutAlignment(algfile=algfile, partfile=partfile, formatin=formatin,
                 format="sequential", colw=10000, colsep="")
    
    ## TODO -- change how cutAlignemnt works to have more robust RegExp here
    lAlg <- list.files(pattern="_(.{2,3})\\.phy$")
    constTr <- read.tree(file=tree)
    for (i in 1:length(lAlg)) {
        algF <- lAlg[i]
        outF <- paste(algF, ".out", sep="")
        testRun <- list.files(pattern=paste("RAxML_.+\\.", outF, sep=""))
        if (length(testRun)) {
            message("File already exist, no need to run RAxML again")
            next
        }
        else {            
            ## Remove empty sequences from individual loci
            nRm <- removeEmptySeqs(algF, #overwrite the files
                                   formatin="sequential", formatout="sequential",
                                   gap="-", quiet=TRUE)
            if (length(nRm)) message("\nFor", algF, "these sequences were removed:",
                                     cat(nRm, sep="\n"),"\n")
            
            ## Drop tips for missing sequence for each individual loci
            tmpAlg <- read.dna(file=algF, format="sequential")
            toDrop <- constTr$tip.label[! constTr$tip.label %in% dimnames(tmpAlg)[[1]]]
            tmpTr <- drop.tip(constTr, toDrop)
            write.tree(tmpTr, file=paste(algF, "tree", sep=""))
            
            ## Estimate parameters for each partition using guide/constrained tree for each
            ## partition.            
            treF <- paste(algF, "tree", sep="")
            cmd <- paste(raxmlCmd, "-s", algF, "-n", outF, "-m", model, "-f e -t", treF, raxmlArg, sep=" ")
            system(cmd)
        }
    }
   
    ## Generate Random sequences
    lInfoFiles <- list.files(pattern="info(.+)out$")
    for (i in 1:length(lInfoFiles)) {
        execSeqGen(getParams(lInfoFiles[i]), nreps=nreps, outputFormat="relaxed")
    }

    resFiles <- list(lAlg = lAlg, lInfo = lInfoFiles)
    
    setwd(owd)
    invisible(resFiles)
}
