
##' This function generates a bash script that runs RAxML on each of
##' the replicated dataset.
##'
##' For now, the bash script generated by this function is not very
##' elegant (to say the least), but it gets the job done.
##'
##' The seed provided or generated is used in all the calls.
##' 
##' @title Generate a bash script
##' @param path path (i.e., directory) where the concatenated datasets are stored.
##' @param output file name (and path if needed) of where the script should be written.
##' @param partfile the partition file to be used for the replicate
##' (WARNING: this is *NOT* the same as the partition file you might
##' have used in your original anlysis, instead use the path for the
##' file that was generated by \code{\link{finalizeAlignments}}).
##' @param model Model of molecular evolution to be used during the
##' likelihood estimation on the replicated datasets (should be the
##' same as the one used for the original analyses.)
##' @param prefix Prefix used to identify the replicated datasets.
##' @param tree If NULL or missing, RAxML will look for the
##' \sQuote{best} tree (use the \sQuote{\code{-f d}} RAxML algorithm),
##' otherwise a character string indicating the file name of a tree to
##' be used as a constraint during the likelihood search (use the
##' \sQuote{\code{-f d -g}} RAxML algorithm).
##' @param seed Seed to be used to initiate the likelihood search in
##' RAxML. If missing a seed is generated.
##' @param raxmlCmd Which flavor of RAxML do you want to use? (default
##' is HPC-PTHREADS-SSE3 version).
##' @param raxmlArg Additional arguments to be passed to RAxML
##' (default "-T7")
##' @return TRUE, but really used for its side effect of generating a
##' bash script that contains the appropriate command to run a
##' likelihood search on each of the replicate dataset.
##' @author Francois Michonneau
##' @export
generateBashScript <- function(path, output, partfile, model,
                               prefix, tree, seed,
                               raxmlCmd="raxmlHPC-PTHREADS-SSE3",
                               raxmlArg="-T7") {
    model <- match.arg(model, c("GTRGAMMA", "GTRGAMMAI"))
    lAlg <- list.files(pattern="rep[0-9]+\\.phy$", path=path)
    reps <- gsub(".+-(.+)\\.phy", "\\1", lAlg)

    if (!length(lAlg)) stop("No alignments found in this path.")
    
    if (missing(seed)) {
        seed <- as.integer(runif(1) * 9999999)        
    }

    if (missing(tree) || is.null(tree)) {
        treecmd <- "-f d" # basic unconstrained
    }
    else {
        treecmd <- paste("-f d -g", tree)
    }

    cmd <- character(length(lAlg))
    for (i in 1:length(lAlg)) {
        cmd[i] <- paste(raxmlCmd, "-s", file.path(path, lAlg[i]), "-m", model,
                        treecmd, "-p", seed, "-q", partfile, "-n",
                        paste(prefix, reps[i], sep="-"), raxmlArg)
    }
    cat(cmd, sep="\n", file=output)
    TRUE
}
