

##' This functions parse the output (info file) of an analysis
##' conducted with RAxML to return the parameters estimated on an
##' alignment as a list.
##'
##' Given an \sQuote{info} file generated by RAxML, this function will
##' return a list that contains all the parameters characterizing the
##' alignement used. This function is specifically (and for now,
##' uniquely) designed to take as an input file, only the RAxML info
##' file generated after invoking the options \dQuote{-f e -t} while
##' using the models of molecular evolution GTRGAMMA, and GTRGAMMAI.
##'
##' Trying to use this function on other types of info files generated
##' by RAxML will most likely not work and might give error messages
##' or not.
##' @title Get alignment characteristics from a RAxML info file
##' @param infoFile path (including file name) of the info file to be
##' parsed.
##' @return A list that includes various characteristics about the
##' alignment:
##' \describe{
##'    \item{alpha}{the shape parameter of
##'       the Gamma distribution for the heterogeneity in rates of
##'       evolution.}
##'    \item{invar}{the proportion of invariant
##'      sites (empty if the GTRGAMMA model is used)}
##'    \item{rateAC, rateAG, rateAT, rateCG, rateGT}{transition
##'      rates for the GTR model}
##'    \item{freqA, freqC, freqG, freqT}{relative proportions of
##'      the these base pairs in the alignement}
##'    \item{nameAlg}{the file name of the alignment file}
##'    \item{treePath}{the file name of the tree with branch lengths
##'       optimized given the parameters of the alignment}
##'    \item{fileNm}{the file name of the info file}
##'    \item{seqlen}{the sequence length}
##' }
##' @author Francois Michonneau
getParams <- function(infoFile) {
    f <- scan(infoFile, what="character", sep="\n",
              quiet=TRUE)

    alpha <- grep("^alpha: ", f, value=TRUE)
    invar <- grep("^invar: ", f, value=TRUE)
    rateAC <- grep("^rate A <-> C: ", f, value=TRUE)
    rateAG <- grep("^rate A <-> G: ", f, value=TRUE)
    rateAT <- grep("^rate A <-> T: ", f, value=TRUE)
    rateCG <- grep("^rate C <-> G: ", f, value=TRUE)
    rateCT <- grep("^rate C <-> T: ", f, value=TRUE)
    rateGT <- grep("^rate G <-> T: ", f, value=TRUE)
    freqA <- grep("^freq pi\\(A\\):", f, value=TRUE)
    freqC <- grep("^freq pi\\(C\\):", f, value=TRUE)
    freqG <- grep("^freq pi\\(G\\):", f, value=TRUE)
    freqT <- grep("^freq pi\\(T\\):", f, value=TRUE)
    treePath <-  grep("Final tree written to: ", f, value=TRUE)
    nameAlg <- grep("-s\\s+(.+\\.phy)", f, value=TRUE)
    nameAlg <- gsub(".+-s\\s(.+\\phy)\\s+.+", "\\1", nameAlg)
    fileNm <- infoFile
    
    res <- list(alpha=alpha, invar=invar,
                rateAC=rateAC, rateAG=rateAG, rateAT=rateAT,
                rateCG=rateCG, rateCT=rateCT, rateGT=rateGT,
                freqA=freqA, freqC=freqC, freqG=freqG, freqT=freqT,
                nameAlg=nameAlg, treePath=treePath, fileNm=fileNm)
    res <- lapply(res, function(x) {
        gsub("(.+)\\s(.+)", "\\2", x)
    })

    algFile <- scan(what="character", file=res$nameAlg, n=1, sep="\n",
                    quiet=TRUE)
    seqlen <- unlist(strsplit(algFile, " "))[2]
    res$seqlen <- seqlen
    
    res
}
