

##' Format Alignment for RAxML input
##'
##' seq-gen generates all replicates in a single file. This function
##' reads the file generated by seq-gen and breaks each replicate into
##' its own file. The files are named by putting together a prefix
##' (specified by the user), the string \sQuote{rep} (stands for
##' replicate), the replicate number, the name of the marker/locus
##' (which should be part of the file name between an underscore and
##' \sQuote{.phy}, e.g., \code{myalignment_marker.phy.out_simSeq}).
##' @title splitSimSeq -- split simulated sequences
##' @param file the path and file name of the simulated file to be broken down.
##' @param prefix the prefix for each of the file name 
##' @param pathin path (i.e., directory) where the replicates for each
##' locus are stored
##' @param pathout path (i.e., directory) where the individual
##' replicate for each locus are going to be stored.
##' @return TRUE, but really used for its side effect of generating
##' individual alignment files.
##' @author Francois Michonneau
splitSimSeq <- function(file, prefix, pathin, pathout) {
    f <- scan(file.path(pathin, file), what="character", sep="\n", quiet=TRUE)

    if (missing(seed)) {
        seed <- as.integer(runif(1) * 10000000)        
    }

    begAlg <- grep("^\\s?[0-9]+\\s{1}[0-9]+$", f)
    endAlg <- c(begAlg[-1] - 1, length(f))
    marker <- grep("phy", unlist(strsplit(file, "_")), value=TRUE)
    marker <- unlist(strsplit(marker, "\\."))[1]
    for (i in 1:length(begAlg)) {
        fileI <- file.path(pathout, paste(prefix, "-rep", i, "-", marker, ".phy", sep=""))
        cat(f[begAlg[i]:endAlg[i]], file=fileI, sep="\n")
    }
    TRUE
}

##' Apply \code{\link{splitSimSeq}} on all loci.
##'
##' Given a regexp pattern that match multiple files representing loci
##' of an alignment simulated by seq-gen, this function applies
##' \code{\link{splitSimSeq}} on each of them.
##'
##' This function may produce a large number of files. If you
##' generated 500 replicates and you have 5 loci, 2,500 files will be
##' generated.
##'
##' If \code{pathout} does not exist, it will be created.
##' @title formatAlignments
##' @param pattern character string that matches the files containing
##' the simulated replicates.
##' @param prefix character string to be appended to each individual
##' file name across all loci
##' @param pathin path (i.e., directory) where the simulated files are
##' located.
##' @param pathout path (i.e., directory) where the the individual
##' replicates will be located.
##' @return TRUE, but really used for its side effect of generating
##' individual replicate for each locus.
##' @author François Michonneau
formatAlignments <- function(pattern, prefix, pathin, pathout) {
    stopifnot(file.exists(pathin))
    pathout <- gsub("/$", "", pathout)
    if (! file.exists(pathout))
        system(paste("mkdir", pathout))
    else if ( ! file.info(pathout)$isdir)
        stop(pathout, " is not a directory.")
        
    lFiles <- list.files(pattern=pattern, path=pathin)
    for (i in 1:length(lFiles)) {
        splitSimSeq(lFiles[i], prefix=prefix, pathin=pathin, pathout=pathout)
    }
    TRUE
}

##' This function concatenate all the loci for a given replicate to
##' produce a single alignment, that will then be used by RAxML to
##' estimate the likelihoods of the constrained and unconstrained
##' topology.
##'
##' Not much that I can think right now.
##' @title Finalize the alignments
##' @param prefix The prefix shared by all the files representing
##' replicates.
##' @param nreps The number of replicates that have been generated. 
##' @param pathin path (i.e., directory) indicating where the files
##' for each locus and each replicates are located.
##' @param pathout path (i.e., directory) indicating where the each of
##' the concatenated replicates will be stored;
##' @return TRUE, but really is used for its side effect of generating
##' alignment files to be used by RAxML.
##' @author François Michonneau
finalizeAlignments <- function(prefix, nreps, pathin, pathout) {
    stopifnot(file.exists(pathin))
    pathout <- gsub("/$", "", pathout)
    if (! file.exists(pathout))
        system(paste("mkdir", pathout))
    else if ( ! file.info(pathout)$isdir)
        stop(pathout, " is not a directory.")
    
    lReps <- list.files(pattern=paste("^", prefix, sep=""), path=pathin)
    partFile <- file.path(pathout, paste(prefix, ".part", sep=""))
    for (i in 1:nreps) {
        ptrn <- paste("^", prefix, "-rep", i, "-", sep="")
        otpt <- file.path(pathout, paste(prefix, "-rep", i, ".phy", sep=""))
        if(i == 1) part <- partFile else part <- NULL
        concatenateAlignments(pattern=ptrn, path=pathin, output=otpt,
                              input.format="sequential",
                              partition=part, partition.format="raxml",
                              format="sequential", standardize=TRUE, colw=10000, colsep="")
    }
    TRUE
}
